apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soundwave
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:dipperpinees/soundwave.git
    targetRevision: master
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://34.124.161.147:6443
    namespace: soundwave
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
