replicaCount: 2

image:
  repository: dipperpinees/soundwave
  tag: "65c60ac223d4257381598edfc9d334375e4b64c9"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: soundwave.boncun.site
      paths:
        - path: /
          pathType: Prefix
  tls: []